defaults:
  - mm_video_template
  - mm_video_distributed_log
  - /dataset@dataset.train: MNISTDataset
  - /dataset@dataset.test: MNISTDataset
  - /dataset@dataset.eval: MNISTDataset
  - /model: CNN
  - /trainer: Trainer
  - /runner: Runner
  - override /hydra/launcher: torchrun

log:
  project_name: mnist_example

dataset:
  train:
    split: train
  test:
    split: test
  eval:
    split: eval

trainer:
  training:
    num_train_epochs: 5
    save_steps: 1000
    eval_steps: 500
    logging_steps: 1

  dataloader:
    num_workers: 8
    train_batch_size: 16
    eval_batch_size: 16

runner:
  do_train: True
  do_test: True
  do_eval: True