defaults:
  - mm_video
  - /dataset@dataset.train: MNISTDataset
  - /dataset@dataset.test: MNISTDataset
  - /dataset@dataset.eval: MNISTDataset
  - /model: CNN

log:
  project_name: mnist_example

dataset:
  train:
    split: train
  test:
    split: test
  eval:
    split: eval

trainer:
  do_train: True
  do_test: True
  do_eval: True

  training:
    num_train_epochs: 5
    resume_from_checkpoint: True
    save_steps: 1000

  dataloader:
    num_workers: 8
    batch_size: 16
