hydra:
  job_logging:
    version: 1
    formatters:
      distributed:
        format: "[%(asctime)s][Rank ${oc.env:RANK,unset}][%(levelname)s] %(name)s %(lineno)d: %(message)s"
      colorful:
        '()': 'colorlog.ColoredFormatter'
        format: "[%(log_color)s%(levelname)s%(reset)s][%(blue)s%(name)s%(reset)s]: %(message)s"
        log_colors:
          DEBUG: purple
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: red
    handlers:
      console:
        level: INFO
        class: logging.StreamHandler
        formatter: colorful
      file:
        level: DEBUG
        formatter: distributed
        filename: "${hydra.runtime.output_dir}/${hydra.job.name}_node_${oc.env:GROUP_RANK,unset}.log"
    root:
      level: INFO
      handlers: [ file, console ]