# @package _global_
defaults:
  - base_config
  - _self_

hydra:
  run:
    dir: "${log.root}/${log.project_name}/${log.experiment_name}"
  sweep:
    dir: "${log.root}/${log.project_name}/multirun"
    subdir: ${hydra.job.override_dirname}
  job_logging:
    version: 1
    formatters:
      mm_video:
        format: "[%(asctime)s][Rank ${oc.env:RANK}][%(levelname)s] %(filename)s %(lineno)d: %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO
      file:
        level: DEBUG
        formatter: mm_video
        filename: "${hydra.runtime.output_dir}/${hydra.job.name}_rank_${oc.env:RANK}.log"
    loggers:
      mm_video:
        level: DEBUG
        handlers: [ file ]
        propagate: no
