# @package _global_
defaults:
  - base_config
  - _self_

hydra:
  run:
    dir: "${log.root}/${log.project_name}/${log.experiment_name}"
  sweep:
    dir: "${log.root}/${log.project_name}/${log.experiment_name}/multirun"
    subdir: ${hydra.job.override_dirname}
  job_logging:
    version: 1
    formatters:
      verbose:
        format: "[%(asctime)s][Rank ${oc.env:RANK}][%(levelname)s] %(name)s %(lineno)d: %(message)s"
      colorful:
        '()': 'colorlog.ColoredFormatter'
        format: "[%(log_color)s%(levelname)s%(reset)s][%(blue)s%(name)s%(reset)s]: %(message)s"
        log_colors:
          DEBUG: purple
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: red
    handlers:
      console:
        level: INFO
        class: logging.StreamHandler
        formatter: colorful
      file:
        level: DEBUG
        formatter: verbose
        filename: "${hydra.runtime.output_dir}/${hydra.job.name}_node_${oc.env:GROUP_RANK}.log"
    root:
      level: DEBUG
      handlers: [ file, console ]
